[package]
name = "testrunner"
version = "0.1.0"
authors = ["Mathias Kahr <m.kahr@student.tugraz.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
horrorshow = "0.8.1"
clap = "2.33.0"
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
subprocess = "0.2.4"
colored = "2.0"
regex = "1.3.6"
diff = "0.1"
toml = "0.5.6"
libloading = "0.6"
signal-hook = "0.1"
wait-timeout = "0.2.0"
