[package]
name = "testrunner"
version = "1.2.19"
authors = ["Thomas Brunner <t.brunner@student.tugraz.at>", "Florian Hager <florian.hager@student.tugraz.at>", "Mathias Kahr <m.kahr@student.tugraz.at>", "Kilian Payer <kilian.payer@student.tugraz.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
clap = "2.33.0"
colored = "2.0"
difference = "2.0.0"
horrorshow = "0.8.1"
libloading = "0.6"
maplit = "1.0.2"
regex = "1.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.3.7"
subprocess = "0.2.6"
termcolor = "1.1.1"
toml = "0.5.6"
uuid = { version = "0.8", features = ["v4"] }

