version: "3"
services:
    builder:
        entrypoint: /bin/bash
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - "./:/app"
